title: XDUNA西电学生网管会
author: XDUNA
email: soowin@qq.com
description: > # this means to ignore newlines until "baseurl:"
  XDUNA网站

github_username:  soowin
google_analytics: UA-150934826-1
sass:
    style: compressed

